### ISSUE TITLE
README 

### ISSUE THREAD

**Issue by Viny2106** [Luisaphysics22/secret_word_game#3]
No terceiro item de regras há um erro de digitação no qual aparece ponto e virgula ao invés do ponto final. O checklist do projeto está incompleto, você precisaria completar e acertar o MARKDOWN.

**Comment by Luisaphysics22** [comment]
Bom dia Vinicius, obrigada por assinalar os erros no README.md do projeto, estarei fazendo as alterações necessárias agora e te informarei que elas foram atualizadas.

**Comment by Luisaphysics22** [comment]
Vinicius gostaria de lhe informar que as devidas alterações já foram feitas. Muito obrigada pela sua contribuição! 😊
